# Generated by Django 3.2 on 2021-05-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_question_question_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-pub_date'], 'verbose_name_plural': 'Questions'},
        ),
    ]
